# Generated by Django 4.0.6 on 2022-07-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('Leido', 'Leido'), ('No Leido', 'No Leido')], default='No Leido', max_length=10),
        ),
    ]
