# Generated by Django 4.0.5 on 2022-07-19 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0004_editpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
